/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.ts" instead.
 */

#include <check.h>

#line 1 "tests.ts"
#include <check.h>
#include "libbuf.h"


float *a;
long *ai;


START_TEST(init_test)
{
#line 11
    /* initialization, buf_free() */
    a = 0;
    ck_assert(buf_capacity(a) == 0);
    ck_assert(buf_size(a) == 0);

}
END_TEST

START_TEST(push_test)
{
#line 17
    a = 0;
    buf_push(a, 1.3f);
    ck_assert(buf_size(a) == 1);
    ck_assert(a[0] == (float)1.3f);

}
END_TEST

START_TEST(clear_test)
{
#line 23
    a = 0;
    buf_push(a, 1.3f);
    buf_clear(a);
    ck_assert(buf_size(a) == 0);
    ck_assert(a != 0);

}
END_TEST

START_TEST(free_test)
{
#line 30
    buf_free(a);
    ck_assert(a == 0);

    /* Clearing an NULL pointer is a no-op */
}
END_TEST

START_TEST(clear_null_test)
{
#line 35
    buf_clear(a);
    ck_assert(buf_size(a) == 0);
    ck_assert(a == 0);

    /* buf_push(), [] operator */
}
END_TEST

START_TEST(indexing_test)
{
#line 41
    ai = 0;
    for (int i = 0; i < 10000; i++)
        buf_push(ai, i);
    ck_assert(buf_size(ai) == 10000);
    int match = 0;
    for (int i = 0; i < (int)(buf_size(ai)); i++)
        match += ai[i] == i;
    ck_assert(match == 10000);
    buf_free(ai);

    /* buf_grow(), buf_trunc() */
}
END_TEST

START_TEST(grow_test)
{
#line 53
    buf_grow(ai, 1000);
    ck_assert(buf_capacity(ai) == 1000);
    ck_assert(buf_size(ai) == 0);

}
END_TEST

START_TEST(trunc_test)
{
#line 58
    buf_trunc(ai, 100);
    ck_assert(buf_capacity(ai) == 100);
    buf_free(ai);

    /* buf_pop() */
}
END_TEST

START_TEST(pop_tase)
{
#line 64
    buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
    ck_assert(buf_size(a) == 4);
    ck_assert(buf_pop(a) == (float)1.4f);
    buf_trunc(a, 3);
    ck_assert(buf_size(a) == 3);
    ck_assert(buf_pop(a) == (float)1.3f);
    ck_assert(buf_pop(a) == (float)1.2f);
    ck_assert(buf_pop(a) == (float)1.1f);
    ck_assert(buf_size(a) == 0);
    buf_free(a);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Tests");
    TCase *tc1_1 = tcase_create("Tests");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, init_test);
    tcase_add_test(tc1_1, push_test);
    tcase_add_test(tc1_1, clear_test);
    tcase_add_test(tc1_1, free_test);
    tcase_add_test(tc1_1, clear_null_test);
    tcase_add_test(tc1_1, indexing_test);
    tcase_add_test(tc1_1, grow_test);
    tcase_add_test(tc1_1, trunc_test);
    tcase_add_test(tc1_1, pop_tase);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
